drop table Illnesses
drop table Vaccinations
drop table Trades
drop table Meals
drop table Deliveries
drop table Animals
drop table Workers
drop table MedicalRecords
drop table Menus
drop table Foods
drop table Suppliers